# Generated by Django 2.1.7 on 2019-06-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.TextField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('imagen', models.URLField()),
                ('autor', models.TextField()),
                ('categoria', models.TextField()),
            ],
            options={
                'ordering': ('titulo', 'fecha'),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.TextField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField(help_text='Debe introducir una edad', verbose_name='Edad')),
                ('sexo', models.CharField(help_text='Debe elegir entre M o F', max_length=1, verbose_name='Sexo')),
                ('codigoPostal', models.TextField(verbose_name='Codigo Postal')),
            ],
            options={
                'ordering': ('idUsuario',),
            },
        ),
    ]
