# Generated by Django 2.2 on 2019-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190605_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.TextField(default='link', verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numerosDeNoticiasBuscadasDeLaCategoriaCultura',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numerosDeNoticiasBuscadasDeLaCategoriaInternacional',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numerosDeNoticiasBuscadasDeLaCategoriaPolitica',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numerosDeNoticiasBuscadasDeLaCategoriaTecnologiaYCiencia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.TextField(verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.TextField(),
        ),
    ]
