# Generated by Django 2.2 on 2019-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190607_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.TextField(null=True, verbose_name='Fecha'),
        ),
    ]
