# Generated by Django 2.2 on 2019-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190607_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
